"use client";

import { ChangeEvent, FormEvent, useCallback, useEffect, useMemo, useRef, useState } from "react";
import { DayPlan, DayStyle, EventItem, Expense, initialDays } from "./trip-data";
import { AttractionGuide, initialGuides } from "./attraction-guides";
import { FoodCity, foodCities } from "./food-guides";

type Ticket = { id:string; eventId:string; name:string; number:string; fileName?:string; fileType?:string; fileData?:string };
type TicketPreview = { data:string; type:string; name:string };
type HeroConfig = { title:string; kicker:string; tripDates:string; hotel:string; backgroundImage?:string; styleTheme?:DayStyle };
type SharedState = { hero:HeroConfig; days:DayPlan[]; guides:AttractionGuide[]; version:number };
type AppData = SharedState & { tickets:Ticket[]; expenses:Expense[] };
type LocalRecord = { base:SharedState; local:Pick<SharedState,"hero"|"days">; tickets:Ticket[]; expenses:Expense[] };
type Tab = "plan" | "attractions" | "expenses" | "edit";

const defaultHero:HeroConfig = { title:"西班牙漫遊", kicker:"ESPAÑA · 18 DÍAS", tripDates:"16 SEP – 03 OCT 2026", hotel:"MADRID · ANDALUCÍA · BARCELONA", styleTheme:"gaudi" };
const defaultShared:SharedState = { hero:defaultHero, days:initialDays, guides:initialGuides, version:0 };
const emptyData:AppData = { ...defaultShared, tickets:[], expenses:[] };
const euroMoney = new Intl.NumberFormat("zh-TW", { style:"currency", currency:"EUR" });
const twdMoney = new Intl.NumberFormat("zh-TW", { style:"currency", currency:"TWD", maximumFractionDigits:0 });
const FALLBACK_EUR_TWD_RATE = 37.31;
const FALLBACK_RATE_DATE = "2026-08-06";
const FONT_SCALE_KEY = "spain-travel-font-scale";
const GUIDE_EVENT_ALIASES:Record<string,string> = {"d1-8":"d3-3","d2-9":"d2-5","d5-9":"d5-5","d9-2":"d8-8","d9-5":"d9-7","d9-6":"d9-7","d10-4":"d10-3","d10-5":"d10-3","d10-6":"d10-3","d10-7":"d10-3","d14-5":"d14-6","d14-7":"d14-6","d14-8":"d14-6"};
const DAY_STYLE_OPTIONS:{id:DayStyle;name:string;description:string;sample:string}[] = [
  {id:"gaudi",name:"高第馬賽克",description:"鈷藍、珊瑚橘與活潑馬賽克圓片",sample:"GAUDÍ"},
  {id:"classic",name:"西班牙經典",description:"赭紅、藏紅花與優雅襯線字",sample:"MADRID"},
  {id:"mediterranean",name:"地中海藍",description:"海水藍、白色與清爽無襯線字",sample:"COSTA"},
  {id:"garden",name:"安達魯西亞花園",description:"橄欖綠、象牙白與柔和斜體",sample:"JARDÍN"},
  {id:"sunset",name:"橙花夕陽",description:"杏桃、暖橘與明亮柔和的南歐色調",sample:"AZAHAR"},
];
const dateLabel = (value:string) => new Intl.DateTimeFormat("zh-TW", { month:"numeric", day:"numeric" }).format(new Date(`${value}T12:00:00`));
const localDateKey = (date = new Date()) => `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}-${String(date.getDate()).padStart(2,"0")}`;
const chooseInitialDate = (days:DayPlan[]) => { const today=localDateKey(); return days.find(day=>day.date===today)?.date || days.find(day=>day.date>today)?.date || days.at(-1)?.date || today; };
const getStartMinutes = (time:string) => { const match=time.match(/(\d{1,2}):(\d{2})/); return match ? Number(match[1])*60+Number(match[2]) : 0; };
const same = (a:unknown,b:unknown) => JSON.stringify(a)===JSON.stringify(b);
const mergeGuideCatalog = (remote?:AttractionGuide[]) => {if(!remote?.length)return initialGuides;const byEvent=new Map(remote.filter(guide=>guide.eventId).map(guide=>[guide.eventId,guide]));const defaults=initialGuides.map(guide=>{const saved=guide.eventId?byEvent.get(guide.eventId):undefined;return saved?.customized?{...saved,date:guide.date,time:guide.time}:guide;});return [...defaults,...remote.filter(guide=>!guide.eventId||!initialGuides.some(item=>item.eventId===guide.eventId))];};

function mergeObject<T extends Record<string,unknown>>(oldBase:T,local:T,newBase:T):T {
  const result={...newBase} as T;
  for(const key of Object.keys(local) as (keyof T)[]) if(!same(local[key],oldBase[key])) result[key]=local[key];
  return result;
}
function mergeShared(oldBase:SharedState,local:Pick<SharedState,"hero"|"days">,next:SharedState){
  const oldDays=new Map(oldBase.days.map(x=>[x.id,x])), localDays=new Map(local.days.map(x=>[x.id,x]));
  const oldEvents=new Map(oldBase.days.flatMap(day=>day.events.map(event=>[event.id,event] as const)));
  const localEvents=new Map(local.days.flatMap(day=>day.events.map(event=>[event.id,event] as const)));
  const days=next.days.flatMap(nextDay=>{const old=oldDays.get(nextDay.id),mine=localDays.get(nextDay.id);if(old&&!mine)return [];const merged=!old||!mine?{...nextDay}:mergeObject(old as unknown as Record<string,unknown>,mine as unknown as Record<string,unknown>,nextDay as unknown as Record<string,unknown>) as unknown as DayPlan;merged.events=nextDay.events.flatMap(nextEvent=>{const oldEvent=oldEvents.get(nextEvent.id),localEvent=localEvents.get(nextEvent.id);if(oldEvent&&!localEvent)return [];if(!oldEvent||!localEvent)return [nextEvent];return [mergeObject(oldEvent as unknown as Record<string,unknown>,localEvent as unknown as Record<string,unknown>,nextEvent as unknown as Record<string,unknown>) as unknown as EventItem];});const localAdditions=(mine?.events||[]).filter(event=>!oldEvents.has(event.id)&&!next.days.some(day=>day.events.some(nextEvent=>nextEvent.id===event.id)));merged.events=[...merged.events,...localAdditions].sort((a,b)=>getStartMinutes(a.time)-getStartMinutes(b.time));return [merged];});
  days.push(...local.days.filter(x=>!oldDays.has(x.id)&&!next.days.some(n=>n.id===x.id)));
  return { hero:mergeObject(oldBase.hero as unknown as Record<string,unknown>,local.hero as unknown as Record<string,unknown>,next.hero as unknown as Record<string,unknown>) as unknown as HeroConfig, days };
}

function openDb(){return new Promise<IDBDatabase>((resolve,reject)=>{const request=indexedDB.open("spain-travel-device",1);request.onupgradeneeded=()=>request.result.createObjectStore("data");request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});}
async function localGet(){const db=await openDb();return new Promise<LocalRecord|undefined>((resolve,reject)=>{const tx=db.transaction("data","readonly");const request=tx.objectStore("data").get("device");request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});}
async function localPut(value:LocalRecord){const db=await openDb();return new Promise<void>((resolve,reject)=>{const tx=db.transaction("data","readwrite");tx.objectStore("data").put(value,"device");tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error);});}
function fileToData(file:File){return new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=()=>reject(reader.error);reader.readAsDataURL(file);});}

async function compressBackground(file:File){
  if(!file.type.startsWith("image/"))throw new Error("Invalid image");
  if(file.size>15*1024*1024)throw new Error("Image too large");
  const objectUrl=URL.createObjectURL(file);
  try{
    const image=await new Promise<HTMLImageElement>((resolve,reject)=>{const next=new Image();next.onload=()=>resolve(next);next.onerror=()=>reject(new Error("Image unavailable"));next.src=objectUrl;});
    const maxSide=1280,scale=Math.min(1,maxSide/Math.max(image.naturalWidth,image.naturalHeight));
    let width=Math.max(1,Math.round(image.naturalWidth*scale)),height=Math.max(1,Math.round(image.naturalHeight*scale)),result="";
    const canvas=document.createElement("canvas"),context=canvas.getContext("2d");
    if(!context)throw new Error("Canvas unavailable");
    for(let attempt=0;attempt<7;attempt++){
      canvas.width=width;canvas.height=height;context.clearRect(0,0,width,height);context.drawImage(image,0,0,width,height);
      for(const quality of [.82,.72,.62,.52,.44]){result=canvas.toDataURL("image/webp",quality);if(result.length<=160000)return result;}
      width=Math.max(480,Math.round(width*.82));height=Math.max(320,Math.round(height*.82));
    }
    return result;
  }finally{URL.revokeObjectURL(objectUrl);}
}

export default function Home(){
  const [data,setData]=useState<AppData>(emptyData),[selectedDate,setSelectedDate]=useState(chooseInitialDate(initialDays));
  const [tab,setTab]=useState<Tab>("plan"),[editingId,setEditingId]=useState<string|null>(null),[dirty,setDirty]=useState(false),[saving,setSaving]=useState(false);
  const [ticketEvent,setTicketEvent]=useState<EventItem|null>(null),[ticketPreview,setTicketPreview]=useState<TicketPreview|null>(null),[guideId,setGuideId]=useState<string|null>(null),[styleEditorOpen,setStyleEditorOpen]=useState(false),[fontEditorOpen,setFontEditorOpen]=useState(false),[heroEditorOpen,setHeroEditorOpen]=useState(false),[loginOpen,setLoginOpen]=useState(false),[toast,setToast]=useState("");
  const [isAdmin,setIsAdmin]=useState(false),[configured,setConfigured]=useState(true),[ready,setReady]=useState(false);
  const [eurTwdRate,setEurTwdRate]=useState(FALLBACK_EUR_TWD_RATE),[rateDate,setRateDate]=useState(FALLBACK_RATE_DATE);
  const [fontScale,setFontScale]=useState(1);
  const eventRefs=useRef<Record<string,HTMLDetailsElement|null>>({}), sharedRef=useRef<SharedState>(defaultShared), overlayRef=useRef<Pick<SharedState,"hero"|"days">>({hero:defaultHero,days:initialDays});
  const day=data.days.find(item=>item.date===selectedDate)||data.days[0],today=localDateKey();
  const flash=(message:string)=>{setToast(message);window.setTimeout(()=>setToast(""),2400);};

  const load=useCallback(async(silent=false)=>{try{
    const [stateResponse,sessionResponse,record]=await Promise.all([fetch("/api/state",{cache:"no-store"}),fetch("/api/auth/session",{cache:"no-store"}),localGet().catch(()=>undefined)]);
    const remoteRaw=await stateResponse.json() as Partial<SharedState>; const remote:SharedState=remoteRaw.days?.length&&remoteRaw.hero?{hero:remoteRaw.hero,days:remoteRaw.days,guides:mergeGuideCatalog(remoteRaw.guides),version:remoteRaw.version||0}:defaultShared;
    const session=await sessionResponse.json() as {admin:boolean;configured:boolean}; sharedRef.current=remote;setIsAdmin(session.admin);setConfigured(session.configured);
    const local=record?mergeShared(record.base,record.local,remote):{hero:remote.hero,days:remote.days};overlayRef.current=record?.local||local;
    setData({...remote,...(session.admin?{hero:remote.hero,days:remote.days}:local),tickets:record?.tickets||[],expenses:record?.expenses||[]});setReady(true);
  }catch{if(!silent)flash("目前使用離線資料");setReady(true);}},[]);
  useEffect(()=>{load();},[load]);
  useEffect(()=>{const saved=Number(localStorage.getItem(FONT_SCALE_KEY));if(saved>=.9&&saved<=1.3)setFontScale(saved);},[]);
  useEffect(()=>{let active=true;fetch("/api/exchange-rate",{cache:"no-store"}).then(response=>response.json()).then((result:{rate?:number;date?:string})=>{if(!active||!result.rate)return;setEurTwdRate(result.rate);if(result.date)setRateDate(result.date);}).catch(()=>{});return()=>{active=false;};},[]);
  useEffect(()=>{if(!history.state?.travelApp)history.replaceState({...history.state,travelApp:true,travelTab:"plan"},"");const handleBack=(event:PopStateEvent)=>{const state=event.state||{};setTicketPreview(null);if(state.travelModal!=="ticket")setTicketEvent(null);if(state.travelModal!=="guide")setGuideId(null);if(state.travelModal!=="style")setStyleEditorOpen(false);if(state.travelModal!=="font")setFontEditorOpen(false);if(state.travelModal!=="hero")setHeroEditorOpen(false);if(state.travelModal!=="login")setLoginOpen(false);setTab(state.travelTab||"plan");};window.addEventListener("popstate",handleBack);return()=>window.removeEventListener("popstate",handleBack);},[]);
  useEffect(()=>{if(tab==="edit"||dirty)return;const timer=window.setInterval(async()=>{try{const response=await fetch("/api/state",{cache:"no-store"});const raw=await response.json() as Partial<SharedState>;if(!raw.days?.length||!raw.hero||raw.version===sharedRef.current.version)return;const next:SharedState={hero:raw.hero,days:raw.days,guides:mergeGuideCatalog(raw.guides),version:raw.version||0};const merged=mergeShared(sharedRef.current,overlayRef.current,next);sharedRef.current=next;if(!isAdmin)setData(current=>({...current,...merged,guides:next.guides,version:next.version}));}catch{}},8000);return()=>clearInterval(timer);},[tab,dirty,isAdmin]);
  useEffect(()=>{if(!ready)return;const timer=window.setTimeout(()=>{if(!isAdmin)overlayRef.current={hero:data.hero,days:data.days};void localPut({base:sharedRef.current,local:overlayRef.current,tickets:data.tickets,expenses:data.expenses});},250);return()=>clearTimeout(timer);},[data,ready,isAdmin]);
  useEffect(()=>{setEditingId(null);},[selectedDate]);

  const nextEventId=useMemo(()=>{if(!day)return undefined;if(selectedDate!==today)return day.events[0]?.id;const now=new Date().getHours()*60+new Date().getMinutes();return day.events.find(event=>getStartMinutes(event.time)>=now)?.id||day.events.at(-1)?.id;},[day,selectedDate,today]);
  function goTab(next:Tab){if(next===tab)return;history.pushState({...history.state,travelApp:true,travelTab:next},"");setTab(next);}
  function openModal(kind:"ticket"|"guide"|"style"|"font"|"hero"|"login",open:()=>void){history.pushState({...history.state,travelApp:true,travelTab:tab,travelModal:kind},"");open();}
  function closeModal(fallback:()=>void){if(history.state?.travelModal)history.back();else fallback();}
  function previewTicket(ticket:Ticket){if(!ticket.fileData)return;const type=ticket.fileType||((ticket.fileName||"").toLowerCase().endsWith(".pdf")?"application/pdf":"application/octet-stream");if(!type.startsWith("image/")){try{const objectUrl=dataUrlToObjectUrl(ticket.fileData,type);const link=document.createElement("a");link.href=objectUrl;link.target="_blank";link.rel="noopener noreferrer";document.body.appendChild(link);link.click();link.remove();window.setTimeout(()=>URL.revokeObjectURL(objectUrl),60000);}catch{flash("檔案無法開啟，請重新加入票券");}return;}history.pushState({...history.state,travelApp:true,travelTab:tab,travelModal:"ticket",travelPreview:true},"");setTicketPreview({data:ticket.fileData,type,name:ticket.fileName||"票券"});}
  function mutateDays(updater:(days:DayPlan[])=>DayPlan[]){setData(current=>({...current,days:updater(current.days)}));setDirty(true);}
  function updateEvent(id:string,patch:Partial<EventItem>){mutateDays(days=>days.map(x=>x.date===selectedDate?{...x,events:x.events.map(e=>e.id===id?{...e,...patch}:e)}:x));}
  function addEvent(event:Omit<EventItem,"id">){mutateDays(days=>days.map(x=>x.date===selectedDate?{...x,events:[...x.events,{...event,id:crypto.randomUUID()}].sort((a,b)=>getStartMinutes(a.time)-getStartMinutes(b.time))}:x));}
  function removeEvent(id:string){mutateDays(days=>days.map(x=>x.date===selectedDate?{...x,events:x.events.filter(e=>e.id!==id)}:x));}
  function updateGuide(id:string,patch:Partial<AttractionGuide>){setData(current=>({...current,guides:current.guides.map(guide=>guide.id===id?{...guide,...patch,customized:true}:guide)}));setDirty(true);}
  function addGuide(){const id=crypto.randomUUID();const guide:AttractionGuide={id,date:selectedDate,time:"12:00",title:"新增景點",icon:"📍",intro:"請填寫景點簡介。",history:"請填寫歷史背景。",tourSteps:["第一個導覽步驟"],sourceLabel:"資料來源",sourceUrl:"https://www.spain.info/en/",customized:true};setData(current=>({...current,guides:[...current.guides,guide]}));setDirty(true);openModal("guide",()=>setGuideId(id));}
  async function applyStyle(styleTheme:DayStyle){setData(current=>({...current,hero:{...current.hero,styleTheme}}));if(!isAdmin)return;try{const shared={...sharedRef.current,hero:{...sharedRef.current.hero,styleTheme}};const response=await fetch("/api/state",{method:"PUT",headers:{"content-type":"application/json; charset=utf-8"},body:JSON.stringify({hero:shared.hero,days:shared.days,guides:shared.guides})});if(!response.ok)throw new Error();const result=await response.json() as {version:number};sharedRef.current={...shared,version:result.version};setData(current=>({...current,version:result.version}));}catch{flash("風格自動儲存失敗，請稍後再試");}}
  async function saveAll(){setSaving(true);try{if(isAdmin){const response=await fetch("/api/state",{method:"PUT",headers:{"content-type":"application/json; charset=utf-8"},body:JSON.stringify({hero:data.hero,days:data.days,guides:data.guides})});if(!response.ok)throw new Error();const result=await response.json();sharedRef.current={hero:data.hero,days:data.days,guides:data.guides,version:result.version};setData(x=>({...x,version:result.version}));flash("已發布，所有人的共用行程與景點導覽將自動更新");}else{overlayRef.current={hero:data.hero,days:data.days};await localPut({base:sharedRef.current,local:overlayRef.current,tickets:data.tickets,expenses:data.expenses});flash("已儲存在這台手機，不會影響其他人");}setDirty(false);}catch{flash("儲存失敗，請稍後再試");}finally{setSaving(false);}}
  async function logout(){await fetch("/api/auth/logout",{method:"POST"});setIsAdmin(false);const merged=mergeShared(sharedRef.current,overlayRef.current,sharedRef.current);setData(x=>({...x,...merged}));setDirty(false);flash("已回到個人模式");}
  const dayExpenses=data.expenses.filter(x=>x.date===selectedDate).reduce((s,x)=>s+x.amount,0),totalExpenses=data.expenses.reduce((s,x)=>s+x.amount,0);
  const sortedGuides=useMemo(()=>[...data.guides].sort((a,b)=>`${a.date} ${a.time}`.localeCompare(`${b.date} ${b.time}`)),[data.guides]);
  const selectedGuide=data.guides.find(guide=>guide.id===guideId)||null;
  const globalStyle=data.hero.styleTheme===("flamenco" as DayStyle)?"sunset":data.hero.styleTheme||"gaudi";

  return <main className={`app-shell app-theme-${globalStyle}`} style={{"--font-scale":fontScale} as React.CSSProperties}>
    <header className={`hero compact hero-style-${globalStyle} ${data.hero.backgroundImage?"has-image":""}`} style={data.hero.backgroundImage?{backgroundImage:`var(--hero-overlay),url(${data.hero.backgroundImage})`}:undefined}><div className="hero-main"><div><p className="eyebrow">{data.hero.kicker}</p><h1>{data.hero.title}</h1></div>{tab==="edit"&&<button className="settings-button hero-settings" onClick={()=>openModal("hero",()=>setHeroEditorOpen(true))} aria-label="修改主畫面">⚙</button>}</div><div className="hero-footer"><div className="trip-meta"><span>{data.hero.tripDates}</span><span>{data.hero.hotel}</span></div><div className="hero-controls"><button className="settings-button style-main-button" onClick={()=>openModal("style",()=>setStyleEditorOpen(true))} aria-label="修改整體風格" title="修改整體風格">🎨</button><button className="settings-button font-main-button" onClick={()=>openModal("font",()=>setFontEditorOpen(true))} aria-label="調整文字大小" title="調整文字大小">Aa</button></div></div></header>
    <section className="date-section"><select id="date-select" aria-label="選擇行程日期" value={selectedDate} onChange={e=>setSelectedDate(e.target.value)}>{data.days.map((x,i)=><option value={x.date} key={x.id}>DAY {i+1} · {dateLabel(x.date)}（{x.weekday}）· {x.theme}{x.date===today?" · 今天":""}</option>)}</select></section>
    {tab==="plan"&&day&&<section className="content plan-view"><DayHeading day={day} onEdit={()=>openModal("style",()=>setStyleEditorOpen(true))}/><div className="status-card"><span className="pulse"/><div><small>{selectedDate===today?"依照現在時間，下一站":"這一天的第一站"}</small><strong>{day.events.find(x=>x.id===nextEventId)?.title}</strong></div><button onClick={()=>eventRefs.current[nextEventId||""]?.scrollIntoView({behavior:"smooth",block:"center"})}>前往</button></div><div className="timeline">{day.events.map(event=>{const tickets=data.tickets.filter(x=>x.eventId===event.id),guideEventId=GUIDE_EVENT_ALIASES[event.id]||event.id,eventGuide=data.guides.find(guide=>guide.eventId===guideEventId);return <details key={event.id} ref={node=>{eventRefs.current[event.id]=node;}} className={`timeline-item ${event.id===nextEventId?"next":""}`}><summary><time>{event.time}</time><span className={`dot ${event.kind||"spot"}`}/><div><h3>{event.title}</h3><p>{event.note}</p></div><span className="chevron">⌄</span></summary><div className="event-actions icon-actions">{eventGuide&&<button aria-label={`開啟 ${eventGuide.title} 景點導覽`} title="景點介紹" onClick={()=>openModal("guide",()=>setGuideId(eventGuide.id))}>🏛️</button>}{event.location&&<a aria-label="Google Maps 導航" title="Google Maps 導航" href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(event.location)}`} target="_blank" rel="noreferrer">➤</a>}{tickets.length>0&&<button aria-label={`開啟 ${tickets.length} 張票券`} title="票券" onClick={()=>openModal("ticket",()=>setTicketEvent(event))}>🎟️</button>}<button aria-label="記一筆花費" title="記一筆花費" onClick={()=>goTab("expenses")}>💰</button></div></details>;})}</div></section>}
    {tab==="attractions"&&<Attractions guides={sortedGuides} foods={foodCities} isAdmin={isAdmin} addGuide={addGuide} openGuide={id=>openModal("guide",()=>setGuideId(id))}/>}
    {tab==="expenses"&&<Expenses data={data} setData={setData} selectedDate={selectedDate} dayExpenses={dayExpenses} totalExpenses={totalExpenses} eurTwdRate={eurTwdRate} rateDate={rateDate} flash={flash}/>}
    {tab==="edit"&&day&&<section className="content edit-view"><div className={`mode-card ${isAdmin?"admin":""}`}><div><small>{isAdmin?"ADMIN MODE":"PERSONAL MODE"}</small><strong>{isAdmin?"管理者共用編輯":"只修改這台手機"}</strong><p>{isAdmin?"儲存後會發布給所有使用者；他們自己的修改仍會保留。":"行程、票券與記帳只存於本機，不會影響其他人。"}</p></div>{isAdmin?<button className="secondary" onClick={logout}>登出</button>:<button className="secondary" onClick={()=>openModal("login",()=>setLoginOpen(true))}>管理者登入</button>}</div><Editor day={day} changeDate={date=>{setEditingId(null);const weekday=["日","一","二","三","四","五","六"][new Date(`${date}T12:00:00`).getDay()];mutateDays(days=>days.map(x=>x.id===day.id?{...x,date,weekday}:x));setSelectedDate(date);}} tickets={data.tickets} setTickets={tickets=>setData(x=>({...x,tickets}))} editingId={editingId} setEditingId={setEditingId} updateEvent={updateEvent} addEvent={addEvent} removeEvent={removeEvent} mutateDays={mutateDays} flash={flash} isAdmin={isAdmin}/></section>}
    <nav className="bottom-nav four"><button className={tab==="plan"?"active":""} onClick={()=>goTab("plan")}><span>◷</span>行程</button><button className={tab==="attractions"?"active":""} onClick={()=>goTab("attractions")}><span>⌾</span>景點</button><button className={tab==="expenses"?"active":""} onClick={()=>goTab("expenses")}><span>€</span>記帳</button><button className={tab==="edit"?"active":""} onClick={()=>goTab("edit")}><span>✎</span>修改</button></nav>
    {tab==="edit"&&dirty&&<div className="save-dock"><span>有尚未儲存的修改</span><button className="primary" disabled={saving} onClick={saveAll}>{saving?"儲存中…":isAdmin?"發布給所有人":"儲存在這台手機"}</button></div>}
    {ticketEvent&&<TicketModal event={ticketEvent} tickets={data.tickets.filter(x=>x.eventId===ticketEvent.id)} preview={ticketPreview} openPreview={previewTicket} closePreview={()=>closeModal(()=>setTicketPreview(null))} close={()=>closeModal(()=>setTicketEvent(null))}/>} 
    {selectedGuide&&<GuideModal guide={selectedGuide} isAdmin={isAdmin} change={patch=>updateGuide(selectedGuide.id,patch)} close={()=>closeModal(()=>setGuideId(null))}/>}
    {styleEditorOpen&&<DayStyleModal selected={globalStyle} isAdmin={isAdmin} choose={styleTheme=>{void applyStyle(styleTheme);}} close={()=>closeModal(()=>setStyleEditorOpen(false))}/>}
    {fontEditorOpen&&<FontSizeModal selected={fontScale} choose={scale=>{setFontScale(scale);localStorage.setItem(FONT_SCALE_KEY,String(scale));}} close={()=>closeModal(()=>setFontEditorOpen(false))}/>}
    {heroEditorOpen&&<HeroEditor hero={data.hero} isAdmin={isAdmin} setHero={hero=>{setData(x=>({...x,hero}));setDirty(true);}} close={()=>closeModal(()=>setHeroEditorOpen(false))} flash={flash}/>} 
    {loginOpen&&<LoginModal configured={configured} close={()=>closeModal(()=>setLoginOpen(false))} success={()=>{closeModal(()=>setLoginOpen(false));setIsAdmin(true);setData(x=>({...x,hero:sharedRef.current.hero,days:sharedRef.current.days,guides:sharedRef.current.guides,version:sharedRef.current.version}));setDirty(false);flash("已進入管理者模式");}}/>}
    {toast&&<div className="toast">✓ {toast}</div>}
  </main>;
}

function Attractions({guides,foods,isAdmin,addGuide,openGuide}:{guides:AttractionGuide[];foods:FoodCity[];isAdmin:boolean;addGuide:()=>void;openGuide:(id:string)=>void}){const [mode,setMode]=useState<"guide"|"food">("guide");return <section className="content feature-view attractions-view"><div className="explore-switch"><button className={mode==="guide"?"active":""} onClick={()=>setMode("guide")}>⌾ 景點導覽</button><button className={mode==="food"?"active":""} onClick={()=>setMode("food")}>🍽️ 美食天地</button></div>{mode==="guide"?<><div className="feature-title attraction-heading"><div><p>GUIDED VISITS · 依行程排序</p><h2>景點導覽</h2><span>點選景點後，依「簡介、歷史、順序導覽」參觀</span></div>{isAdmin&&<button className="primary" onClick={addGuide}>＋ 新增景點</button>}</div><div className="attraction-list">{guides.map((guide,index)=><button className="attraction-card" key={guide.id} onClick={()=>openGuide(guide.id)}><span className="attraction-icon" aria-hidden="true">{guide.icon}</span><div><small>STOP {String(index+1).padStart(2,"0")} · {dateLabel(guide.date)} · {guide.time}</small><h3>{guide.title}</h3><p>{guide.intro}</p></div><b>›</b></button>)}</div>{!isAdmin&&<p className="guide-admin-hint">管理員可在「修改」頁登入後，新增景點或編輯全部導覽內容。</p>}</>:<FoodWorld cities={foods}/>}</section>}

function FoodWorld({cities}:{cities:FoodCity[]}){
  const [cityId,setCityId]=useState<string|null>(null);
  useEffect(()=>{setCityId(history.state?.foodCity||null);const handleBack=(event:PopStateEvent)=>setCityId(event.state?.foodCity||null);window.addEventListener("popstate",handleBack);return()=>window.removeEventListener("popstate",handleBack);},[]);
  const city=cities.find(item=>item.id===cityId);
  const openCity=(id:string)=>{history.pushState({...history.state,travelApp:true,travelTab:"attractions",foodCity:id},"");setCityId(id);};
  const backToCities=()=>{if(history.state?.foodCity)history.back();else setCityId(null);};
  if(city)return <div className="food-world"><button className="food-back" onClick={backToCities}>← 返回所有城市</button><div className="feature-title food-heading"><div><p>{city.dates} · {city.restaurants.length} 間推薦</p><h2>{city.icon} {city.name}美食</h2><span>{city.summary}</span></div></div><div className="restaurant-list">{city.restaurants.map(restaurant=><details className="restaurant-card" key={restaurant.id}><summary><span className="restaurant-icon">{restaurant.icon}</span><div><small>{restaurant.area}</small><h3>{restaurant.name}</h3><b>{restaurant.price}</b></div><i>⌄</i></summary><div className="restaurant-detail"><p>{restaurant.feature}</p><h4>推薦菜色</h4><div className="dish-tags">{restaurant.dishes.map(dish=><span key={dish}>{dish}</span>)}</div>{restaurant.note&&<small className="food-note">提醒：{restaurant.note}</small>}<a href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(restaurant.location)}`} target="_blank" rel="noreferrer">➤ 開啟 Google Maps 導航</a></div></details>)}</div></div>;
  return <div className="food-world"><div className="feature-title food-heading"><div><p>ESPAÑA FLAVOURS · 依旅程排序</p><h2>美食天地</h2><span>先選城市，再查看餐廳特色、推薦菜色、價位與導航。</span></div></div><p className="food-disclaimer">價位為每人概估；菜單、營業時間與價格可能調整，熱門餐廳請事先訂位。</p><div className="food-city-list">{cities.map((item,index)=><button className="food-city-card" key={item.id} onClick={()=>openCity(item.id)}><span>{item.icon}</span><div><small>STOP {String(index+1).padStart(2,"0")} · {item.dates}</small><h3>{item.name}</h3><p>{item.summary}</p><b>{item.restaurants.length} 間推薦</b></div><i>›</i></button>)}</div></div>;
}

function GuideModal({guide,isAdmin,change,close}:{guide:AttractionGuide;isAdmin:boolean;change:(patch:Partial<AttractionGuide>)=>void;close:()=>void}){const [section,setSection]=useState<"intro"|"history"|"tour">("intro"),[editing,setEditing]=useState(false);return <div className="modal-backdrop guide-backdrop"><section className="ticket-modal guide-modal"><div className="modal-title"><div className="guide-title"><span>{guide.icon}</span><div><small>{dateLabel(guide.date)} · {guide.time}</small><h2>{guide.title}</h2></div></div><button onClick={close} aria-label="關閉景點導覽">×</button></div>{editing?<div className="guide-edit form-grid"><label>圖案<input value={guide.icon} onChange={event=>change({icon:event.target.value})}/></label><label>時間<input value={guide.time} onChange={event=>change({time:event.target.value})}/></label><label className="wide">日期<input type="date" value={guide.date} onChange={event=>change({date:event.target.value})}/></label><label className="wide">景點名稱<input value={guide.title} onChange={event=>change({title:event.target.value})}/></label><label className="wide">簡介<textarea value={guide.intro} onChange={event=>change({intro:event.target.value})}/></label><label className="wide">歷史<textarea value={guide.history} onChange={event=>change({history:event.target.value})}/></label><label className="wide">順序導覽（每行一個步驟）<textarea className="guide-steps-input" value={guide.tourSteps.join("\n")} onChange={event=>change({tourSteps:event.target.value.split("\n").filter(Boolean)})}/></label><label className="wide">資料來源名稱<input value={guide.sourceLabel} onChange={event=>change({sourceLabel:event.target.value})}/></label><label className="wide">資料來源網址<input inputMode="url" value={guide.sourceUrl} onChange={event=>change({sourceUrl:event.target.value})}/></label><button className="primary wide" onClick={()=>setEditing(false)}>完成編輯</button></div>:<><div className="guide-tabs"><button className={section==="intro"?"active":""} onClick={()=>setSection("intro")}>簡介</button><button className={section==="history"?"active":""} onClick={()=>setSection("history")}>歷史</button><button className={section==="tour"?"active":""} onClick={()=>setSection("tour")}>順序導覽</button></div><div className="guide-content">{section==="intro"&&<><h3>先認識這一站</h3><p>{guide.intro}</p></>}{section==="history"&&<><h3>歷史背景</h3><p>{guide.history}</p></>}{section==="tour"&&<><h3>跟著順序參觀</h3><ol>{guide.tourSteps.map((step,index)=><li key={`${guide.id}-${index}`}><span>{index+1}</span><p>{step}</p></li>)}</ol></>}<a className="guide-source" href={guide.sourceUrl} target="_blank" rel="noreferrer">參考資料：{guide.sourceLabel} ↗</a></div>{isAdmin&&<button className="secondary guide-edit-button" onClick={()=>setEditing(true)}>✎ 修改圖案與導覽文字</button>}</>}</section></div>}

function DayStyleModal({selected,isAdmin,choose,close}:{selected:DayStyle;isAdmin:boolean;choose:(style:DayStyle)=>void;close:()=>void}){return <div className="modal-backdrop style-backdrop"><section className="ticket-modal style-modal"><div className="modal-title"><div><small>APP STYLE</small><h2>選擇整體風格</h2></div><button onClick={close} aria-label="關閉風格選擇">×</button></div><p className="style-description">點選後會立即套用、自動儲存並關閉。{isAdmin?"管理者選擇會同步給所有人。":"只會保存在這台手機。"}</p><div className="style-options">{DAY_STYLE_OPTIONS.map(option=><button key={option.id} className={`style-option preview-${option.id} ${selected===option.id?"selected":""}`} onClick={()=>{choose(option.id);close();}}><span className="style-check">{selected===option.id?"✓":""}</span><small>{option.description}</small><strong>{option.sample}</strong><b>{option.name}</b></button>)}</div></section></div>}

function FontSizeModal({selected,choose,close}:{selected:number;choose:(scale:number)=>void;close:()=>void}){const options=[{value:.9,label:"較小"},{value:1,label:"標準"},{value:1.1,label:"大"},{value:1.2,label:"特大"},{value:1.3,label:"最大"}];return <div className="modal-backdrop"><section className="ticket-modal font-modal"><div className="modal-title"><div><small>TEXT SIZE · 本機設定</small><h2>調整文字大小</h2></div><button onClick={close} aria-label="關閉文字大小設定">×</button></div><p className="style-description">點選後立即套用並保存在這台手機；底部導覽維持固定大小。</p><div className="font-size-options">{options.map(option=><button key={option.value} className={selected===option.value?"selected":""} onClick={()=>{choose(option.value);close();}}><span style={{fontSize:`${16*option.value}px`}}>Aa</span><b>{option.label}</b>{selected===option.value&&<i>✓</i>}</button>)}</div><div className="font-preview" style={{fontSize:`${16*selected}px`}}><small>預覽文字</small><strong>今天前往聖家堂參觀</strong><p>點開行程即可查看景點介紹、票券與導航。</p></div></section></div>}

function DayHeading({day,onEdit}:{day:DayPlan;onEdit:()=>void}){const style=day.styleTheme||"classic";return <div className={`section-heading day-styled day-style-${style} ${day.backgroundImage?"day-cover":""}`} style={day.backgroundImage?{backgroundImage:`var(--day-overlay),url(${day.backgroundImage})`}:undefined}><div><p>{dateLabel(day.date)} · 星期{day.weekday}</p><h2>{day.theme}</h2><span>{day.subtitle}</span></div><button className="day-style-button" onClick={onEdit} aria-label="修改每日標題風格">🎨 修改</button></div>}

function LoginModal({configured,close,success}:{configured:boolean;close:()=>void;success:()=>void}){const [username,setUsername]=useState("admin"),[password,setPassword]=useState(""),[error,setError]=useState(""),[loading,setLoading]=useState(false);async function submit(e:FormEvent){e.preventDefault();setLoading(true);setError("");const response=await fetch("/api/auth/login",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({username,password})});if(response.ok)success();else setError((await response.json()).error||"登入失敗");setLoading(false);}return <div className="modal-backdrop"><section className="ticket-modal settings-modal"><div className="modal-title"><div><small>ADMIN</small><h2>管理者登入</h2></div><button onClick={close} aria-label="關閉">×</button></div>{!configured&&<p className="form-error">網站尚未設定管理者環境變數。</p>}<form className="form-grid" onSubmit={submit}><label className="wide">帳號<input autoComplete="username" value={username} onChange={e=>setUsername(e.target.value)}/></label><label className="wide">密碼<input type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)}/></label>{error&&<p className="form-error wide">{error}</p>}<button className="primary wide" disabled={loading||!configured}>{loading?"登入中…":"登入"}</button></form></section></div>}

function TicketModal({event,tickets,preview,openPreview,closePreview,close}:{event:EventItem;tickets:Ticket[];preview:TicketPreview|null;openPreview:(t:Ticket)=>void;closePreview:()=>void;close:()=>void}){return <div className="modal-backdrop"><section className="ticket-modal"><div className="modal-title"><div><small>MY TICKETS · 本機離線</small><h2>{event.title}</h2></div><button onClick={close} aria-label="關閉票券">×</button></div><div className="ticket-list">{tickets.map(ticket=><article className="ticket-card compact-ticket" key={ticket.id}><div className="ticket-top"><span>ADMIT ONE</span><b>已存於此裝置</b></div><p>{ticket.fileName||"票券"}</p>{ticket.fileData&&ticket.fileType?.startsWith("image/")&&<button className="ticket-image-button" onClick={()=>openPreview(ticket)} aria-label="放大票券圖片"><img src={ticket.fileData} alt={ticket.fileName||"票券圖片"}/></button>}{ticket.fileData&&!ticket.fileType?.startsWith("image/")&&<button className="file-link file-open-button" onClick={()=>openPreview(ticket)}>開啟檔案</button>}</article>)}</div></section>{preview&&<LocalFilePreview preview={preview} close={closePreview}/>}</div>}

function dataUrlToObjectUrl(dataUrl:string,mimeType:string){const comma=dataUrl.indexOf(",");if(comma<0)throw new Error("Invalid local file");const header=dataUrl.slice(0,comma),payload=dataUrl.slice(comma+1);const binary=header.includes(";base64")?atob(payload):decodeURIComponent(payload);const bytes=new Uint8Array(binary.length);for(let index=0;index<binary.length;index++)bytes[index]=binary.charCodeAt(index);return URL.createObjectURL(new Blob([bytes],{type:mimeType}));}

function LocalFilePreview({preview,close}:{preview:TicketPreview;close:()=>void}){const [objectUrl,setObjectUrl]=useState("");useEffect(()=>{let url="";try{url=dataUrlToObjectUrl(preview.data,preview.type);setObjectUrl(url);}catch{setObjectUrl("");}return()=>{if(url)URL.revokeObjectURL(url);};},[preview]);const isImage=preview.type.startsWith("image/");return <div className="file-lightbox"><div className="file-preview-header"><strong>{preview.name}</strong><button onClick={close} aria-label="關閉檔案預覽">×</button></div><div className="file-preview-stage">{isImage?<img className="preview-image" src={objectUrl||preview.data} alt={preview.name}/>:objectUrl?<iframe src={objectUrl} title={preview.name}/>:<p>檔案無法開啟，請重新加入票券。</p>}</div></div>}

function Expenses({data,setData,selectedDate,dayExpenses,totalExpenses,eurTwdRate,rateDate,flash}:{data:AppData;setData:React.Dispatch<React.SetStateAction<AppData>>;selectedDate:string;dayExpenses:number;totalExpenses:number;eurTwdRate:number;rateDate:string;flash:(s:string)=>void}){const [title,setTitle]=useState(""),[amount,setAmount]=useState("") ,[category,setCategory]=useState("餐飲");function add(e:FormEvent){e.preventDefault();if(!Number(amount))return;setData(x=>({...x,expenses:[...x.expenses,{id:crypto.randomUUID(),date:selectedDate,title:title.trim(),amount:Number(amount),category}]}));setTitle("");setAmount("");flash("已記錄在這台手機");}return <section className="content feature-view"><div className="feature-title"><div><p>EXPENSES · 本機資料</p><h2>旅費記帳</h2><span>每個人的花費各自保存在自己的裝置</span></div></div><div className="money-grid"><article><small>當日花費</small><strong>{euroMoney.format(dayExpenses)}</strong><span className="twd-equivalent">約 {twdMoney.format(dayExpenses*eurTwdRate)}</span></article><article className="dark"><small>總花費</small><strong>{euroMoney.format(totalExpenses)}</strong><span className="twd-equivalent">約 {twdMoney.format(totalExpenses*eurTwdRate)}</span></article></div><p className="exchange-note">參考匯率：€1 ≈ NT${eurTwdRate.toFixed(2)}（{rateDate.replaceAll("-","/")} 更新），實際換匯或刷卡金額可能不同。</p><form className="panel expense-form form-grid" onSubmit={add}><h3 className="wide">新增花費</h3><label>分類<select value={category} onChange={e=>setCategory(e.target.value)}><option>餐飲</option><option>門票</option><option>交通</option><option>購物</option><option>其他</option></select></label><label>金額（EUR）<input inputMode="decimal" value={amount} onChange={e=>setAmount(e.target.value)}/></label><label className="wide">項目（選填）<input value={title} onChange={e=>setTitle(e.target.value)} placeholder="可以不填"/></label><button className="primary wide">加入</button></form><div className="panel expense-list">{data.expenses.filter(x=>x.date===selectedDate).map(x=><article key={x.id}><span>€</span><div><h3>{x.title||"未填項目"}</h3><p>{x.category}</p></div><strong>{euroMoney.format(x.amount)}</strong><button onClick={()=>setData(d=>({...d,expenses:d.expenses.filter(e=>e.id!==x.id)}))}>×</button></article>)}</div></section>}

function Editor({day,changeDate,tickets,setTickets,editingId,setEditingId,updateEvent,addEvent,removeEvent,mutateDays,flash,isAdmin}:{day:DayPlan;changeDate:(s:string)=>void;tickets:Ticket[];setTickets:(t:Ticket[])=>void;editingId:string|null;setEditingId:(s:string|null)=>void;updateEvent:(id:string,p:Partial<EventItem>)=>void;addEvent:(e:Omit<EventItem,"id">)=>void;removeEvent:(id:string)=>void;mutateDays:(u:(d:DayPlan[])=>DayPlan[])=>void;flash:(s:string)=>void;isAdmin:boolean}){
  const [coverOpen,setCoverOpen]=useState(false);
  useEffect(()=>{setCoverOpen(false);},[day.id]);
  return <>
    <section className={`panel day-edit ${coverOpen?"open":""}`}>
      <button type="button" className="editor-section-toggle" aria-expanded={coverOpen} onClick={()=>setCoverOpen(open=>!open)}><span><strong>日期與當日封面</strong><small>{dateLabel(day.date)} · {day.theme}</small></span><b>{coverOpen?"⌃":"⌄"}</b></button>
      {coverOpen&&<div className="day-edit-fields"><label>日期<input type="date" value={day.date} onChange={e=>changeDate(e.target.value)}/></label><label>標題<input value={day.theme} onChange={e=>mutateDays(ds=>ds.map(x=>x.id===day.id?{...x,theme:e.target.value}:x))}/></label><label>副標題<input value={day.subtitle} onChange={e=>mutateDays(ds=>ds.map(x=>x.id===day.id?{...x,subtitle:e.target.value}:x))}/></label><BackgroundUploader current={day.backgroundImage} isAdmin={isAdmin} onUploaded={url=>mutateDays(ds=>ds.map(x=>x.id===day.id?{...x,backgroundImage:url}:x))} onClear={()=>mutateDays(ds=>ds.map(x=>x.id===day.id?{...x,backgroundImage:undefined}:x))} flash={flash}/></div>}
    </section>
    <div className="edit-list">{day.events.map(event=>{const open=editingId===event.id;const kindLabel=event.kind==="food"?"餐廳":event.kind==="transit"?"交通":event.kind==="rest"?"休息":"景點";return <article className={`edit-card ${open?"panel open":""}`} key={event.id}><button type="button" className="edit-card-toggle" aria-expanded={open} onClick={()=>setEditingId(open?null:event.id)}><time>{event.time}</time><span className={`dot ${event.kind||"spot"}`} aria-hidden="true"/><span className="edit-card-copy"><strong>{event.title}</strong><small>{kindLabel}{tickets.some(x=>x.eventId===event.id)?" · 有本機票券":""}</small></span><b className="chevron">⌄</b></button>{open&&<div className="edit-card-body"><div className="form-grid"><label>時間<input value={event.time} onChange={e=>updateEvent(event.id,{time:e.target.value})}/></label><label>類型<select value={event.kind} onChange={e=>updateEvent(event.id,{kind:e.target.value as EventItem["kind"]})}><option value="spot">景點</option><option value="food">餐廳</option><option value="transit">交通</option><option value="rest">休息</option></select></label><label className="wide">名稱<input value={event.title} onChange={e=>updateEvent(event.id,{title:e.target.value})}/></label><label className="wide">細節<textarea value={event.note} onChange={e=>updateEvent(event.id,{note:e.target.value})}/></label><label className="wide">Google Maps 地點<input value={event.location||""} onChange={e=>updateEvent(event.id,{location:e.target.value})}/></label></div><TicketAdmin event={event} tickets={tickets.filter(x=>x.eventId===event.id)} allTickets={tickets} setTickets={setTickets} flash={flash}/><div className="edit-actions"><button type="button" className="danger" onClick={()=>{removeEvent(event.id);setEditingId(null);}}>刪除行程</button><button type="button" className="primary" onClick={()=>setEditingId(null)}>收起修改</button></div></div>}</article>})}</div>
    <AddEventForm addEvent={addEvent}/>
  </>;
}

function AddEventForm({addEvent}:{addEvent:(e:Omit<EventItem,"id">)=>void}){const [open,setOpen]=useState(false),[time,setTime]=useState("09:00"),[title,setTitle]=useState(""),[note,setNote]=useState(""),[location,setLocation]=useState(""),[kind,setKind]=useState<EventItem["kind"]>("spot");if(!open)return <button className="primary" onClick={()=>setOpen(true)}>＋ 新增景點或餐廳</button>;return <form className="panel form-grid add-form" onSubmit={e=>{e.preventDefault();if(!title)return;addEvent({time,title,note,location,kind});setTitle("");setOpen(false);}}><h3 className="wide">新增行程</h3><label>時間<input value={time} onChange={e=>setTime(e.target.value)}/></label><label>類型<select value={kind} onChange={e=>setKind(e.target.value as EventItem["kind"])}><option value="spot">景點</option><option value="food">餐廳</option><option value="transit">交通</option><option value="rest">休息</option></select></label><label className="wide">名稱<input value={title} onChange={e=>setTitle(e.target.value)}/></label><label className="wide">細節<textarea value={note} onChange={e=>setNote(e.target.value)}/></label><label className="wide">Google Maps 地點<input value={location} onChange={e=>setLocation(e.target.value)}/></label><div className="edit-actions wide"><button type="button" className="secondary" onClick={()=>setOpen(false)}>取消</button><button className="primary">加入行程</button></div></form>}

function HeroEditor({hero,setHero,close,flash,isAdmin}:{hero:HeroConfig;setHero:(h:HeroConfig)=>void;close:()=>void;flash:(s:string)=>void;isAdmin:boolean}){return <div className="modal-backdrop"><section className="ticket-modal settings-modal"><div className="modal-title"><div><small>HOME SETTINGS</small><h2>修改主畫面</h2></div><button onClick={close} aria-label="關閉">×</button></div><div className="form-grid"><label className="wide">主標題<input value={hero.title} onChange={e=>setHero({...hero,title:e.target.value})}/></label><label>英文小標<input value={hero.kicker} onChange={e=>setHero({...hero,kicker:e.target.value})}/></label><label>住宿標籤<input value={hero.hotel} onChange={e=>setHero({...hero,hotel:e.target.value})}/></label><label className="wide">日期標籤<input value={hero.tripDates} onChange={e=>setHero({...hero,tripDates:e.target.value})}/></label></div><BackgroundUploader current={hero.backgroundImage} isAdmin={isAdmin} onUploaded={url=>setHero({...hero,backgroundImage:url})} onClear={()=>setHero({...hero,backgroundImage:undefined})} flash={flash}/><button className="primary settings-done" onClick={close}>完成設定</button></section></div>}

function BackgroundUploader({current,onUploaded,onClear,flash,isAdmin}:{current?:string;onUploaded:(s:string)=>void;onClear:()=>void;flash:(s:string)=>void;isAdmin:boolean}){const [loading,setLoading]=useState(false);async function upload(e:ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];if(!file)return;setLoading(true);try{onUploaded(await compressBackground(file));flash(isAdmin?"共用封面已加入，按發布後所有人即可看到":"封面已儲存在這台手機");}catch{flash("圖片處理失敗，請選擇 15 MB 以下的圖片");}finally{setLoading(false);}}return <div className="background-control">{current&&<img src={current} alt="封面預覽"/>}<label className="secondary"><input type="file" accept="image/*" onChange={upload}/>{loading?"壓縮中…":current?"更換背景":"新增背景"}</label>{current&&<button className="danger" onClick={onClear}>移除</button>}</div>}

function TicketAdmin({event,tickets,allTickets,setTickets,flash}:{event:EventItem;tickets:Ticket[];allTickets:Ticket[];setTickets:(t:Ticket[])=>void;flash:(s:string)=>void}){const [file,setFile]=useState<File|null>(null),[loading,setLoading]=useState(false);async function upload(e:FormEvent){e.preventDefault();if(!file)return flash("請選擇票券圖片或 PDF");if(file.size>12*1024*1024)return flash("單一檔案請小於 12 MB");setLoading(true);try{const ticket:Ticket={id:crypto.randomUUID(),eventId:event.id,name:file.name,number:"",fileName:file.name,fileType:file.type,fileData:await fileToData(file)};setTickets([...allTickets,ticket]);setFile(null);flash("票券已離線儲存在這台裝置");}catch{flash("票券儲存失敗");}finally{setLoading(false);}}return <div className="ticket-admin"><h3>我的離線票券</h3>{tickets.map(x=><div className="admin-ticket" key={x.id}><span>🎟️</span><div><b>{x.fileName||"票券"}</b><small>儲存在這台手機</small></div><button onClick={()=>setTickets(allTickets.filter(t=>t.id!==x.id))} aria-label="刪除票券">×</button></div>)}<form className="form-grid" onSubmit={upload}><label className="upload wide"><input type="file" accept="image/*,.pdf" onChange={e=>setFile(e.target.files?.[0]||null)}/><span>{file?file.name:"點選加入 QR Code、圖片或 PDF"}</span></label><button className="secondary wide" disabled={loading||!file}>{loading?"儲存中…":"儲存在這台手機"}</button></form></div>}
