export type EventItem = { id: string; time: string; title: string; note: string; location?: string; kind?: "spot" | "food" | "transit" | "rest" };
export type DayStyle = "classic" | "mediterranean" | "garden" | "gaudi" | "flamenco";
export type DayPlan = { id: string; date: string; weekday: string; theme: string; subtitle: string; backgroundImage?: string; styleTheme?: DayStyle; events: EventItem[] };
export type Expense = { id: string; date: string; category: string; title: string; amount: number };

export const initialDays: DayPlan[] = [
  { id:"day-1", date:"2026-09-16", weekday:"三", theme:"抵達馬德里・麗池公園・老城散步", subtitle:"馬德里｜住宿基準：阿托查／文學區", events:[
    { id:"d1-1", time:"13:30", title:"班機抵達馬德里巴拉哈斯機場", note:"移動：入境、領行李。預留約 90 分鐘；先確認抵達航廈", kind:"transit" },
    { id:"d1-2", time:"15:00–15:50", title:"前往住宿區", note:"移動：第四航廈搭近郊鐵路 C1/C10 約 30–35 分；其他航廈可搭機場快線。大行李可改搭固定費率計程車｜費用：近郊鐵路／快線約 €5；計程車約 €33／車", kind:"transit" },
    { id:"d1-3", time:"16:00–16:35", title:"入住／寄放行李、短休息", note:"不安排需預約景點", kind:"transit" },
    { id:"d1-4", time:"16:40–17:50", title:"麗池公園、湖區散步", note:"移動：飯店步行或計程車約 10–15 分。若班機延誤，縮短為 40–50 分鐘｜門票：免費", location:"麗池公園、湖區散步, 馬德里, Spain", kind:"spot" },
    { id:"d1-5", time:"18:00–18:20", title:"前往太陽門", note:"移動：地鐵＋步行約 15–20 分。避開尖峰擠車", kind:"transit" },
    { id:"d1-6", time:"18:20–19:00", title:"太陽門、主廣場", note:"移動：步行約 8 分。慢慢適應時差｜門票：免費", location:"太陽門、主廣場, 馬德里, Spain", kind:"spot" },
    { id:"d1-7", time:"19:00–19:40", title:"聖米格爾市場簡單用餐", note:"移動：主廣場步行約 3 分。先補充水分｜市場入場免費；餐飲另計", location:"聖米格爾市場簡單用餐, 馬德里, Spain", kind:"food" },
    { id:"d1-8", time:"19:45–20:20", title:"皇宮與阿穆德納聖母主教座堂外觀", note:"移動：市場步行約 8–10 分。正式入內安排隔天｜僅看外觀：免費", location:"皇宮與阿穆德納聖母主教座堂外觀, 馬德里, Spain", kind:"spot" },
    { id:"d1-9", time:"20:30", title:"老城晚餐、返回飯店", note:"移動：步行＋地鐵約 20–25 分。第一晚不排晚場", location:"老城晚餐、返回飯店, 馬德里, Spain", kind:"food" },
  ]},
  { id:"day-2", date:"2026-09-17", weekday:"四", theme:"塞哥維亞一日遊", subtitle:"馬德里往返｜住宿基準：阿托查／文學區", events:[
    { id:"d2-1", time:"07:20", title:"早餐、帶輕便小包", note:"大行李留飯店", location:"早餐、帶輕便小包, 馬德里, Spain", kind:"food" },
    { id:"d2-2", time:"07:50-08:20", title:"前往 馬德里查馬丁站", note:"移動：近郊鐵路／地鐵，約 15-25 分。至少提前 30 分抵達", kind:"transit" },
    { id:"d2-3", time:"08:30-09:15", title:"馬德里 → 塞哥維亞吉奧馬爾站", note:"移動：Renfe AVE／Avlo；約 27-35 分。近期常見上午有多班｜火車：單程近期約 €10–30", kind:"transit" },
    { id:"d2-4", time:"09:15-09:35", title:"車站 → 古羅馬水道橋", note:"移動：市區公車 11／12 約 15-20 分；計程車約 10 分。高鐵站位於郊外｜公車約 €2–3；計程車約 €10／車", kind:"transit" },
    { id:"d2-5", time:"09:40-11:00", title:"古羅馬水道橋、老城入口", note:"先拍全景｜門票：免費", location:"古羅馬水道橋、老城入口, 馬德里, Spain", kind:"spot" },
    { id:"d2-6", time:"11:10-12:00", title:"主廣場、塞哥維亞主教堂", note:"移動：步行 8-12 分。依票況入內｜門票：近期約 €4", location:"主廣場、塞哥維亞主教堂, 馬德里, Spain", kind:"spot" },
    { id:"d2-7", time:"12:10-13:30", title:"烤乳豬午餐", note:"熱門餐廳需訂位", location:"烤乳豬午餐, 馬德里, Spain", kind:"food" },
    { id:"d2-8", time:"13:45-15:30", title:"塞哥維亞城堡 城堡", note:"移動：步行約 12 分。塔樓另購票｜城堡約 €10；塔樓另約 €3", location:"塞哥維亞城堡 城堡, 馬德里, Spain", kind:"spot" },
    { id:"d2-9", time:"15:30-17:15", title:"猶太區、老城與水道橋補拍", note:"保留咖啡時間", location:"猶太區、老城與水道橋補拍, 馬德里, Spain", kind:"spot" },
    { id:"d2-10", time:"17:30-19:30", title:"返回 塞哥維亞吉奧馬爾站 → 馬德里", note:"移動：公車／計程車＋Renfe。依實際車次平移｜回程火車單程約 €10–30", kind:"transit" },
  ]},
  { id:"day-3", date:"2026-09-18", weekday:"五", theme:"馬德里皇宮・普拉多・市中心＋德波神廟", subtitle:"馬德里｜住宿基準：阿托查／文學區", events:[
    { id:"d3-1", time:"08:30", title:"早餐、整理票券", note:"皇宮 QR 碼離線保存", location:"早餐、整理票券, 馬德里, Spain", kind:"food" },
    { id:"d3-2", time:"09:10–09:40", title:"前往馬德里皇宮", note:"移動：地鐵／計程車約 10–15 分。09:40 前抵達安檢", kind:"transit" },
    { id:"d3-3", time:"10:00–11:30", title:"馬德里皇宮", note:"移動：已購票入場。固定 10:00｜票券已購", location:"馬德里皇宮, 馬德里, Spain", kind:"spot" },
    { id:"d3-4", time:"11:35–12:10", title:"阿穆德納聖母主教座堂", note:"移動：步行 2 分。一般區域多為免費", location:"阿穆德納聖母主教座堂, 馬德里, Spain", kind:"spot" },
    { id:"d3-5", time:"12:15–13:30", title:"主廣場周邊午餐", note:"移動：步行 10 分。下午安排普拉多", location:"主廣場周邊午餐, 馬德里, Spain", kind:"food" },
    { id:"d3-6", time:"13:40–14:10", title:"前往普拉多博物館", note:"移動：步行約 25 分／計程車 10 分。預留安檢", kind:"transit" },
    { id:"d3-7", time:"14:30–17:00", title:"普拉多博物館", note:"移動：預約入場。門票近期約 €15", location:"普拉多博物館, 馬德里, Spain", kind:"spot" },
    { id:"d3-8", time:"17:05–18:10", title:"西貝萊斯廣場、格蘭大道、西班牙廣場", note:"移動：步行＋短程地鐵。麗池公園已在第 1 天", location:"西貝萊斯廣場、格蘭大道、西班牙廣場, 馬德里, Spain", kind:"spot" },
    { id:"d3-9", time:"18:10–18:25", title:"前往德波神廟", note:"移動：步行約 8–10 分。日落前約 45 分抵達", kind:"transit" },
    { id:"d3-10", time:"18:25–20:20", title:"德波神廟夕陽、晚餐", note:"免費", location:"德波神廟夕陽、晚餐, 馬德里, Spain", kind:"food" },
  ]},
  { id:"day-4", date:"2026-09-19", weekday:"六", theme:"托雷多一日遊", subtitle:"馬德里往返｜住宿基準：阿托查／文學區", events:[
    { id:"d4-1", time:"07:30", title:"早餐、帶輕便小包", note:"大行李留飯店", location:"早餐、帶輕便小包, 馬德里, Spain", kind:"food" },
    { id:"d4-2", time:"08:10", title:"抵達 阿托查 車站", note:"移動：住宿區步行約 5-12 分。至少提前 30 分過安檢", kind:"transit" },
    { id:"d4-3", time:"08:45-09:15", title:"馬德里 → 托雷多", note:"移動：Renfe Avant；約 33 分。近期常見票價單程約 €14｜火車：單程近期約 €14", kind:"transit" },
    { id:"d4-4", time:"09:30-09:45", title:"車站 → 索科多韋爾廣場", note:"移動：計程車約 8-10 分。不建議一早徒步爬坡｜計程車約 €8–10／車", kind:"transit" },
    { id:"d4-5", time:"09:45-12:00", title:"索科多韋爾廣場、主教堂", note:"移動：景點間步行 5-10 分。主教堂預留 75 分鐘｜主教座堂門票近期約 €12", location:"索科多韋爾廣場、主教堂, 馬德里, Spain", kind:"spot" },
    { id:"d4-6", time:"12:15-13:20", title:"午餐", note:"午餐後進猶太區", location:"午餐, 馬德里, Spain", kind:"food" },
    { id:"d4-7", time:"13:30-16:20", title:"聖多美教堂、猶太區、聖若望皇家修道院", note:"移動：總步行約 25-35 分。穿防滑鞋｜聖多美約 €4；聖若望修道院約 €4–5", location:"聖多美教堂、猶太區、聖若望皇家修道院, 馬德里, Spain", kind:"spot" },
    { id:"d4-8", time:"16:30-17:20", title:"河谷觀景台", note:"移動：計程車約 10 分。拍照後直接去車站｜計程車約 €10–15／車；觀景免費", location:"河谷觀景台, 馬德里, Spain", kind:"spot" },
    { id:"d4-9", time:"18:30-19:30", title:"托雷多 → 馬德里", note:"移動：Renfe Avant；約 33 分。近期常見來回約 €22-25｜回程火車單程約 €14", kind:"transit" },
  ]},
  { id:"day-5", date:"2026-09-20", weekday:"日", theme:"馬德里→哥多華→塞維亞＋都市陽傘夜景", subtitle:"塞維亞｜住宿基準：聖十字區／赫雷斯門", events:[
    { id:"d5-1", time:"07:30", title:"早餐、退房", note:"每人 1 箱；確認車票", location:"早餐、退房, 塞維亞, Spain", kind:"food" },
    { id:"d5-2", time:"08:15", title:"抵達馬德里阿托查－阿穆德納格蘭德斯站", note:"移動：步行／計程車。至少提前 30–40 分", kind:"transit" },
    { id:"d5-3", time:"09:00–10:57", title:"馬德里 → 哥多華", note:"移動：已購火車票。阿托查－阿穆德納格蘭德斯→哥多華－胡里奧安吉塔", kind:"transit" },
    { id:"d5-4", time:"11:00–11:30", title:"寄放行李、前往舊城", note:"移動：計程車約 8–10 分。先確認寄存點", kind:"transit" },
    { id:"d5-5", time:"11:35–13:00", title:"猶太區、百花巷、羅馬橋", note:"移動：步行 5–12 分。免費；避開正午禮拜時段", location:"猶太區、百花巷、羅馬橋, 塞維亞, Spain", kind:"spot" },
    { id:"d5-6", time:"13:00–14:25", title:"午餐／休息", note:"清真寺 15:00 才開放觀光", location:"午餐／休息, 塞維亞, Spain", kind:"food" },
    { id:"d5-7", time:"14:30–14:50", title:"前往清真寺主教座堂、排隊安檢", note:"14:45 前抵達", kind:"transit" },
    { id:"d5-8", time:"15:00–16:30", title:"哥多華清真寺主教座堂", note:"移動：預約入場。中午禮拜後 15:00 開放｜門票近期約 €13", location:"哥多華清真寺主教座堂, 塞維亞, Spain", kind:"spot" },
    { id:"d5-9", time:"16:35–17:10", title:"羅馬橋或老城補拍", note:"依晚班火車時間縮短", location:"羅馬橋或老城補拍, 塞維亞, Spain", kind:"spot" },
    { id:"d5-10", time:"17:10–17:40", title:"返回車站、領行李", note:"移動：計程車約 8–10 分。預留進站時間", kind:"transit" },
    { id:"d5-11", time:"18:00–19:00", title:"哥多華 → 塞維亞", note:"移動：Avant／AVE 約 45–55 分。建議訂 18:00 後班次｜€13–35／人", kind:"transit" },
    { id:"d5-12", time:"19:15–19:45", title:"入住塞維亞飯店", note:"移動：計程車約 10–15 分。兩人約 €10–15", kind:"transit" },
    { id:"d5-13", time:"20:15–21:15", title:"都市陽傘夜景", note:"移動：步行／計程車。門票近期約 €15；依正式開放時間", location:"都市陽傘夜景, 塞維亞, Spain", kind:"spot" },
    { id:"d5-14", time:"21:20", title:"附近晚餐、返回飯店", note:"不再安排其他付費景點", location:"附近晚餐、返回飯店, 塞維亞, Spain", kind:"food" },
  ]},
  { id:"day-6", date:"2026-09-21", weekday:"一", theme:"塞維亞完整精華日", subtitle:"塞維亞｜住宿基準：聖十字區／赫雷斯門", events:[
    { id:"d6-1", time:"08:15", title:"早餐、前往王宮入口", note:"移動：步行 5–12 分。08:40 到場安檢", location:"早餐、前往王宮入口, 塞維亞, Spain", kind:"food" },
    { id:"d6-2", time:"09:00–10:50", title:"塞維亞王宮", note:"移動：預約入場。門票：近期約 €15；花園留 30 分鐘", location:"塞維亞王宮, 塞維亞, Spain", kind:"spot" },
    { id:"d6-3", time:"11:00–11:15", title:"聖十字區巷弄", note:"免費；沿路前往大教堂", location:"聖十字區巷弄, 塞維亞, Spain", kind:"spot" },
    { id:"d6-4", time:"11:30–13:05", title:"塞維亞大教堂＋吉拉達塔", note:"移動：預約入場。門票：近期約 €13", location:"塞維亞大教堂＋吉拉達塔, 塞維亞, Spain", kind:"spot" },
    { id:"d6-5", time:"13:15–14:15", title:"午餐", note:"避開景點正門餐廳", location:"午餐, 塞維亞, Spain", kind:"food" },
    { id:"d6-6", time:"14:30–16:15", title:"西班牙廣場、瑪麗亞路易莎公園", note:"移動：步行／電車。免費；電車約 €1.4–2", location:"西班牙廣場、瑪麗亞路易莎公園, 塞維亞, Spain", kind:"spot" },
    { id:"d6-7", time:"16:30–17:45", title:"黃金塔外觀、特里亞納市場與河岸", note:"移動：步行／必要時計程車。免費為主；黃金塔與河岸可縮短", location:"黃金塔外觀、特里亞納市場與河岸, 塞維亞, Spain", kind:"food" },
    { id:"d6-8", time:"18:00–19:45", title:"休息、提早吃西班牙小菜", note:"保留佛朗明哥進場緩衝", kind:"rest" },
    { id:"d6-9", time:"20:30–22:00", title:"佛朗明哥表演", note:"移動：步行／計程車。票價：近期約 €25–45", location:"佛朗明哥表演, 塞維亞, Spain", kind:"spot" },
  ]},
  { id:"day-7", date:"2026-09-22", weekday:"二", theme:"塞維亞第二天・特里亞納・河岸・在地街區", subtitle:"塞維亞｜住宿基準：聖十字區／赫雷斯門", events:[
    { id:"d7-1", time:"08:30", title:"早餐、慢慢出發", note:"不安排早場門票", location:"早餐、慢慢出發, 塞維亞, Spain", kind:"food" },
    { id:"d7-2", time:"09:30–11:00", title:"皮拉托之家／舊城街區（二選一）", note:"門票近期約 €12；不想入內可改街區散步", location:"皮拉托之家／舊城街區（二選一）, 塞維亞, Spain", kind:"spot" },
    { id:"d7-3", time:"11:15–12:30", title:"特里亞納市場", note:"移動：步行過橋／計程車。市場免費；適合早午餐", location:"特里亞納市場, 塞維亞, Spain", kind:"food" },
    { id:"d7-4", time:"12:30–14:00", title:"特里亞納區散步、午餐", note:"陶瓷街、巷弄", location:"特里亞納區散步、午餐, 塞維亞, Spain", kind:"food" },
    { id:"d7-5", time:"14:15–15:00", title:"黃金塔外觀、瓜達幾維河河岸", note:"免費；不必登塔", location:"黃金塔外觀、瓜達幾維河河岸, 塞維亞, Spain", kind:"spot" },
    { id:"d7-6", time:"15:00–17:30", title:"回飯店休息／自由活動", note:"隔天自駕，保留體力", kind:"rest" },
    { id:"d7-7", time:"17:30–19:00", title:"塞維亞市中心補逛、咖啡", note:"可依體力取消", location:"塞維亞市中心補逛、咖啡, 塞維亞, Spain", kind:"food" },
    { id:"d7-8", time:"19:00–20:30", title:"提早晚餐", note:"整理隔日行李", location:"提早晚餐, 塞維亞, Spain", kind:"food" },
    { id:"d7-9", time:"20:30", title:"確認赫茲訂單與導航", note:"移動：飯店。取車地址：Parking Eeff Saba 2，聖胡斯塔車站", location:"確認赫茲訂單與導航, 塞維亞, Spain", kind:"spot" },
  ]},
  { id:"day-8", date:"2026-09-23", weekday:"三", theme:"塞維亞→塞特尼爾→龍達", subtitle:"龍達｜住宿基準：新橋附近", events:[
    { id:"d8-1", time:"07:45", title:"早餐、退房", note:"駕照、國際駕照、信用卡", location:"早餐、退房, 龍達, Spain", kind:"food" },
    { id:"d8-2", time:"08:25–08:45", title:"前往赫茲塞維亞聖胡斯塔車站據點", note:"移動：計程車約 10–15 分。地址：Parking Eeff Saba 2, Sevilla 41007", kind:"transit" },
    { id:"d8-3", time:"09:00–09:30", title:"取車、驗車、設定導航", note:"移動：Hertz 櫃檯。已預約；錄影車身、輪圈、油量", kind:"transit" },
    { id:"d8-4", time:"09:30–11:20", title:"塞維亞 → 塞特尼爾", note:"移動：自駕約 1 小時 45–55 分。行李全放後車廂", kind:"transit" },
    { id:"d8-5", time:"11:25–13:30", title:"塞特尼爾岩壁街區＋午餐", note:"移動：停車後步行。街區免費；停車依公告", location:"塞特尼爾岩壁街區＋午餐, 龍達, Spain", kind:"food" },
    { id:"d8-6", time:"13:30–14:05", title:"塞特尼爾 → 龍達", note:"移動：自駕約 25–35 分。進城後停飯店或公有停車場", kind:"transit" },
    { id:"d8-7", time:"14:15–14:45", title:"寄放行李／入住", note:"保留下午完整逛龍達", kind:"transit" },
    { id:"d8-8", time:"14:45–18:45", title:"新橋、老城、觀景台、舊橋", note:"移動：步行 5–20 分。主要觀景免費", location:"新橋、老城、觀景台、舊橋, 龍達, Spain", kind:"spot" },
    { id:"d8-9", time:"19:00–20:30", title:"夕陽、晚餐", note:"翌日 13:40 國王步道", location:"夕陽、晚餐, 龍達, Spain", kind:"food" },
  ]},
  { id:"day-9", date:"2026-09-24", weekday:"四", theme:"龍達→國王步道 13:40 場→格拉納達火車站還車", subtitle:"格拉納達｜住宿基準：市中心／雷阿萊霍區", events:[
    { id:"d9-1", time:"07:30", title:"早餐、退房", note:"運動鞋、水、輕便補給", location:"早餐、退房, 格拉納達, Spain", kind:"food" },
    { id:"d9-2", time:"08:10–10:00", title:"龍達新橋、老城補逛", note:"10:00 後取車離開", location:"龍達新橋、老城補逛, 格拉納達, Spain", kind:"spot" },
    { id:"d9-3", time:"10:10–11:30", title:"龍達 → 埃爾喬羅南端出口停車場", note:"移動：自駕約 1 小時 10–20 分。先到出口端停車", kind:"transit" },
    { id:"d9-4", time:"11:30–12:00", title:"停車、簡單午餐／補給", note:"移動：自備最穩妥。不要壓縮接駁時間", location:"停車、簡單午餐／補給, 格拉納達, Spain", kind:"food" },
    { id:"d9-5", time:"12:00–12:35", title:"南端搭官方接駁至北端", note:"移動：接駁約 25–35 分。近期約 €2.5／人", location:"南端搭官方接駁至北端, 格拉納達, Spain", kind:"spot" },
    { id:"d9-6", time:"12:35–13:20", title:"走至檢票口、領安全帽", note:"移動：步行約 20–30 分。13:20 前抵達", location:"走至檢票口、領安全帽, 格拉納達, Spain", kind:"spot" },
    { id:"d9-7", time:"13:40–16:40", title:"國王步道", note:"移動：已購固定場次。單向約 3 小時", location:"國王步道, 格拉納達, Spain", kind:"spot" },
    { id:"d9-8", time:"16:45–18:45", title:"埃爾喬羅 → 格拉納達", note:"移動：自駕約 1 小時 40–2 小時。預留加油與市區交通", kind:"transit" },
    { id:"d9-9", time:"18:45–19:20", title:"加滿油、前往格拉納達火車站赫茲", note:"移動：自駕。還車地址：Avda de los Andaluces s/n", kind:"transit" },
    { id:"d9-10", time:"19:20–20:00", title:"辦理還車", note:"移動：Hertz 櫃檯。先確認據點關門與是否接受下班後鑰匙箱", kind:"transit" },
    { id:"d9-11", time:"20:00–20:20", title:"火車站 → 市區飯店", note:"移動：計程車約 10–15 分。兩人約 €8–15", kind:"transit" },
    { id:"d9-12", time:"20:30", title:"入住、附近晚餐", note:"不再安排景點", location:"入住、附近晚餐, 格拉納達, Spain", kind:"food" },
  ]},
  { id:"day-10", date:"2026-09-25", weekday:"五", theme:"阿爾罕布拉宮＋格拉納達舊城", subtitle:"格拉納達｜阿爾罕布拉宮結束後完成舊城行程", events:[
    { id:"d10-1", time:"08:00", title:"早餐、帶水與薄外套", note:"護照姓名須與票券一致", location:"早餐、帶水與薄外套, 格拉納達, Spain", kind:"food" },
    { id:"d10-2", time:"08:45–09:10", title:"市中心 → 阿爾罕布拉宮", note:"移動：C30 小巴約 15–20 分。可提前入園", kind:"transit" },
    { id:"d10-3", time:"09:15–10:30", title:"赫內拉利費宮與花園", note:"移動：步行 15–20 分。先逛不受 12:00 定時限制區域", location:"赫內拉利費宮與花園, 格拉納達, Spain", kind:"spot" },
    { id:"d10-4", time:"10:35–11:25", title:"阿爾卡薩瓦城堡／卡洛斯五世宮", note:"11:30 前往納斯里德宮入口", location:"阿爾卡薩瓦城堡／卡洛斯五世宮, 格拉納達, Spain", kind:"spot" },
    { id:"d10-5", time:"11:30–11:55", title:"納斯里德宮入口排隊", note:"不可錯過票面時段", location:"納斯里德宮入口排隊, 格拉納達, Spain", kind:"spot" },
    { id:"d10-6", time:"12:00–13:00", title:"納斯里德宮", note:"移動：已購固定時段。12:00 準時入場", location:"納斯里德宮, 格拉納達, Spain", kind:"spot" },
    { id:"d10-7", time:"13:10–14:00", title:"園區補逛、拍照", note:"依體力調整", location:"園區補逛、拍照, 格拉納達, Spain", kind:"spot" },
    { id:"d10-8", time:"14:15–15:15", title:"雷阿萊霍區午餐", note:"移動：步行下山或 C30。膝蓋不舒服搭車", location:"雷阿萊霍區午餐, 格拉納達, Spain", kind:"food" },
    { id:"d11-2", time:"15:30–16:40", title:"格拉納達主教座堂、皇家禮拜堂", note:"移動：步行約 10 分。依最後入場時間彈性調整", location:"格拉納達主教座堂、皇家禮拜堂, 格拉納達, Spain", kind:"spot" },
    { id:"d11-3", time:"16:45–17:20", title:"阿爾凱塞里亞市集、聖奧古斯丁市場", note:"移動：步行 3–5 分。市場營業時間以當日公告為準", location:"阿爾凱塞里亞市集、聖奧古斯丁市場, 格拉納達, Spain", kind:"food" },
    { id:"d11-4", time:"17:30–18:45", title:"達羅河谷街、阿爾拜辛下緣", note:"沿平緩路線散步，不爬到最高處，保留體力", location:"達羅河谷街、阿爾拜辛下緣, 格拉納達, Spain", kind:"spot" },
    { id:"d10-9", time:"18:50–19:30", title:"茶館區／自由散步", note:"在舊城休息、喝茶，不再安排大型付費景點", location:"茶館區／自由散步, 格拉納達, Spain", kind:"rest" },
    { id:"d10-10", time:"20:00", title:"晚餐、整理隔天行李", note:"翌日一早退房前往馬拉加", location:"晚餐、整理隔天行李, 格拉納達, Spain", kind:"food" },
  ]},
  { id:"day-11", date:"2026-09-26", weekday:"六", theme:"一早前往馬拉加・古城・城堡・海港", subtitle:"馬拉加｜當日完成全部馬拉加行程", events:[
    { id:"d11-1", time:"06:45", title:"早餐、退房", note:"前一晚整理好行李，只帶輕便早餐", location:"早餐、退房, 格拉納達, Spain", kind:"food" },
    { id:"d11-6", time:"07:20–07:45", title:"飯店 → 格拉納達巴士站", note:"移動：計程車約 15–20 分。提前到站", kind:"transit" },
    { id:"d11-7", time:"08:00–09:50", title:"格拉納達 → 馬拉加", note:"移動：ALSA 早班直達巴士；實際班次與票價依正式車票", kind:"transit" },
    { id:"d11-8", time:"10:00–10:30", title:"馬拉加巴士站 → 飯店寄放行李", note:"移動：步行／計程車，先寄放行李再出發", kind:"transit" },
    { id:"d12-2", time:"10:45–11:35", title:"希布拉法羅城堡", note:"移動：公車／計程車上山，避免徒步上坡", location:"希布拉法羅城堡, 馬拉加, Spain", kind:"spot" },
    { id:"d12-3", time:"11:45–13:00", title:"阿爾卡薩瓦城堡、羅馬劇場", note:"移動：由城堡往下參觀，依現場開放時間調整", location:"阿爾卡薩瓦城堡、羅馬劇場, 馬拉加, Spain", kind:"spot" },
    { id:"d12-4", time:"13:10–14:00", title:"阿塔拉薩納斯中央市場／午餐", note:"移動：步行約 10 分。星期六請留意市場收攤時間", location:"阿塔拉薩納斯中央市場／午餐, 馬拉加, Spain", kind:"food" },
    { id:"d12-5", time:"14:15–15:30", title:"馬拉加畢卡索博物館", note:"建議事先預約入場；依票面時段調整前後行程", location:"馬拉加畢卡索博物館, 馬拉加, Spain", kind:"spot" },
    { id:"d12-6", time:"15:40–16:40", title:"馬拉加主教座堂、老城", note:"依體力與最後入場時間決定是否入內", location:"馬拉加主教座堂、老城, 馬拉加, Spain", kind:"spot" },
    { id:"d12-7", time:"17:00–19:00", title:"馬拉蓋塔海灘、一號碼頭", note:"移動：步行／公車。看夕陽後在港口用餐", location:"馬拉蓋塔海灘、一號碼頭, 馬拉加, Spain", kind:"spot" },
    { id:"d11-10", time:"19:15", title:"晚餐、返回飯店休息", note:"確認隔日 12:20 航班與托運資料", location:"一號碼頭, 馬拉加, Spain", kind:"food" },
  ]},
  { id:"day-12", date:"2026-09-27", weekday:"日", theme:"馬拉加→巴塞隆納＋哥德區／國家宮夜景", subtitle:"巴塞隆納｜航班 12:20 出發・13:55 抵達", events:[
    { id:"d13-1", time:"08:00", title:"早餐、退房", note:"行李整理成可直接登機", location:"早餐、退房, 巴塞隆納, Spain", kind:"food" },
    { id:"d13-2", time:"09:15–10:00", title:"市區 → 馬拉加機場", note:"移動：近郊鐵路 C1／計程車。至少提前約 2 小時到機場", kind:"transit" },
    { id:"d13-3", time:"12:20–13:55", title:"馬拉加 → 巴塞隆納", note:"航班固定時間：12:20 出發、13:55 抵達", kind:"transit" },
    { id:"d13-4", time:"13:55–15:15", title:"領行李、前往市區飯店", note:"移動：機場巴士約 35–45 分。約 €8–10／人", kind:"transit" },
    { id:"d13-5", time:"15:15–16:15", title:"寄放行李、午餐", note:"依實際航班平移", location:"寄放行李、午餐, 巴塞隆納, Spain", kind:"food" },
    { id:"d13-6", time:"16:30–18:30", title:"哥德區、聖雅各廣場", note:"街區免費", location:"哥德區、聖雅各廣場, 巴塞隆納, Spain", kind:"spot" },
    { id:"d13-7", time:"18:30–19:15", title:"蘭布拉大道短逛、早晚餐", note:"聖荷西市場留到 9/30", location:"蘭布拉大道短逛、早晚餐, 巴塞隆納, Spain", kind:"food" },
    { id:"d13-8", time:"19:15–19:45", title:"前往西班牙廣場", note:"移動：地鐵約 15–20 分。約 €2.5", kind:"transit" },
    { id:"d13-9", time:"20:00–21:30", title:"國家宮階梯、蒙特惠奇夜景", note:"不把水舞當成固定演出", location:"國家宮階梯、蒙特惠奇夜景, 巴塞隆納, Spain", kind:"spot" },
    { id:"d13-10", time:"21:30", title:"回飯店休息", note:"移動：地鐵。翌日高第建築日", kind:"rest" },
  ]},
  { id:"day-13", date:"2026-09-28", weekday:"一", theme:"奎爾公園・聖十字聖保羅醫院・聖家堂＋巴特婁之家", subtitle:"巴塞隆納｜高第與現代主義建築日", events:[
    { id:"d14-1", time:"08:00–09:30", title:"奎爾公園", note:"移動：地鐵／公車＋步行。建議訂早場；門票近期約 €18", location:"奎爾公園, 巴塞隆納, Spain", kind:"spot" },
    { id:"d14-2", time:"09:30–10:15", title:"前往聖十字聖保羅醫院", note:"移動：計程車／公車。控制轉乘時間", kind:"transit" },
    { id:"d14-3", time:"10:15–11:30", title:"聖十字聖保羅醫院", note:"移動：預約入場。門票近期約 €18", location:"聖十字聖保羅醫院, 巴塞隆納, Spain", kind:"spot" },
    { id:"d14-4", time:"11:30–12:20", title:"午餐／前往聖家堂", note:"移動：步行約 10–15 分。12:20 後不再排遠距離景點", location:"午餐／前往聖家堂, 巴塞隆納, Spain", kind:"food" },
    { id:"d14-5", time:"12:45–13:30", title:"聖家堂周邊、安檢", note:"至少提前 20 分到場", location:"聖家堂周邊、安檢, 巴塞隆納, Spain", kind:"spot" },
    { id:"d14-6", time:"13:45", title:"聖家堂入場", note:"移動：已購票。固定 13:45", location:"聖家堂入場, 巴塞隆納, Spain", kind:"spot" },
    { id:"d14-7", time:"14:30", title:"登塔", note:"移動：已購票。依票面塔樓與集合點", location:"登塔, 巴塞隆納, Spain", kind:"spot" },
    { id:"d14-8", time:"15:00–16:15", title:"繼續參觀聖家堂", note:"彩窗與博物館", location:"繼續參觀聖家堂, 巴塞隆納, Spain", kind:"spot" },
    { id:"d14-9", time:"16:15–17:00", title:"咖啡、休息", note:"預留體力", location:"咖啡、休息, 巴塞隆納, Spain", kind:"food" },
    { id:"d14-10", time:"17:00–18:15", title:"巴特婁之家", note:"移動：預約入場。門票近期約 €35–45", location:"巴特婁之家, 巴塞隆納, Spain", kind:"spot" },
    { id:"d14-11", time:"18:20–18:45", title:"米拉之家外觀", note:"移動：步行約 8–10 分。不入內，免費", location:"米拉之家外觀, 巴塞隆納, Spain", kind:"spot" },
    { id:"d14-12", time:"19:00", title:"格拉西亞大道晚餐", note:"結束高強度行程", location:"格拉西亞大道晚餐, 巴塞隆納, Spain", kind:"food" },
  ]},
  { id:"day-14", date:"2026-09-29", weekday:"二", theme:"蒙特塞拉特山景一日遊", subtitle:"巴塞隆納往返｜修道院、黑面聖母與山景步道", events:[
    { id:"d15-1", time:"07:30", title:"早餐、前往西班牙廣場站", note:"移動：地鐵。帶薄外套與水", location:"早餐、前往西班牙廣場站, 巴塞隆納, Spain", kind:"food" },
    { id:"d15-2", time:"08:20–09:30", title:"巴塞隆納 → 蒙特塞拉特空中纜車站", note:"移動：R5 火車。班次以當日為準", kind:"transit" },
    { id:"d15-3", time:"09:30–09:50", title:"搭空中纜車上山", note:"移動：空中纜車。強風停駛時改齒軌火車", location:"搭空中纜車上山, 巴塞隆納, Spain", kind:"spot" },
    { id:"d15-4", time:"10:00–11:30", title:"修道院、黑面聖母", note:"依預約時段", location:"修道院、黑面聖母, 巴塞隆納, Spain", kind:"spot" },
    { id:"d15-5", time:"11:30–12:30", title:"午餐／簡單補給", note:"山上餐飲較貴", location:"午餐／簡單補給, 巴塞隆納, Spain", kind:"food" },
    { id:"d15-6", time:"12:30–15:00", title:"聖米格爾十字架步道", note:"Sant Joan 停駛替代方案", location:"聖米格爾十字架步道, 巴塞隆納, Spain", kind:"spot" },
    { id:"d15-7", time:"15:00–16:00", title:"修道院周邊自由活動", note:"不搭最後一班下山", kind:"rest" },
    { id:"d15-8", time:"16:00–18:00", title:"返回巴塞隆納", note:"移動：纜車＋R5。預留轉乘", kind:"transit" },
    { id:"d15-9", time:"19:00", title:"晚餐、休息", note:"翌日巴塞隆納舊城與魔幻噴泉", location:"晚餐、休息, 巴塞隆納, Spain", kind:"food" },
  ]},
  { id:"day-15", date:"2026-09-30", weekday:"三", theme:"聖荷西市場・哥德區・博恩區＋魔幻噴泉", subtitle:"巴塞隆納｜市場、舊城街區與蒙特惠奇夜景", events:[
    { id:"d17-1", time:"08:30–09:00", title:"前往聖荷西市場", note:"移動：地鐵 L3／步行。早到避開團客", location:"前往聖荷西市場, 巴塞隆納, Spain", kind:"food" },
    { id:"d17-2", time:"09:00–10:15", title:"聖荷西市場早餐與參觀", note:"市場入場免費，餐飲另計", location:"聖荷西市場早餐與參觀, 巴塞隆納, Spain", kind:"food" },
    { id:"d17-3", time:"10:15–11:00", title:"蘭布拉大道、皇家廣場", note:"免費", location:"蘭布拉大道、皇家廣場, 巴塞隆納, Spain", kind:"spot" },
    { id:"d17-4", time:"11:00–12:15", title:"哥德區、巴塞隆納主教座堂", note:"主教座堂開放與票價以當日公告為準", location:"哥德區、巴塞隆納主教座堂, 巴塞隆納, Spain", kind:"spot" },
    { id:"d17-5", time:"12:15–13:00", title:"聖卡特琳娜市場", note:"移動：步行約 10 分，可簡單補給", location:"聖卡特琳娜市場, 巴塞隆納, Spain", kind:"food" },
    { id:"d17-6", time:"13:00–14:00", title:"午餐", note:"避開主街觀光餐廳", location:"午餐, 巴塞隆納, Spain", kind:"food" },
    { id:"d17-7", time:"14:00–15:10", title:"海洋聖母教堂、博恩區", note:"依教堂當日開放公告參觀", location:"海洋聖母教堂、博恩區, 巴塞隆納, Spain", kind:"spot" },
    { id:"d17-8", time:"15:15–16:45", title:"巴塞隆納畢卡索博物館（選配）", note:"建議預約入場；若休息不足可改為咖啡時間", location:"巴塞隆納畢卡索博物館, 巴塞隆納, Spain", kind:"spot" },
    { id:"d17-9", time:"17:00–18:00", title:"城堡公園、凱旋門", note:"免費", location:"城堡公園、凱旋門, 巴塞隆納, Spain", kind:"spot" },
    { id:"d17-10", time:"18:00–19:10", title:"提早晚餐", note:"為晚間行程保留移動時間", location:"提早晚餐, 巴塞隆納, Spain", kind:"food" },
    { id:"d17-11", time:"19:10–19:45", title:"前往西班牙廣場", note:"移動：地鐵約 20 分", kind:"transit" },
    { id:"d17-12", time:"20:00–21:30", title:"魔幻噴泉／國家宮夜景", note:"須依 2026 官方場次確認；無水舞演出就改看國家宮夜景", location:"魔幻噴泉／國家宮夜景, 巴塞隆納, Spain", kind:"spot" },
    { id:"d17-13", time:"21:30", title:"返回飯店休息", note:"翌日濱海托薩一日遊", kind:"transit" },
  ]},
  { id:"day-16", date:"2026-10-01", weekday:"四", theme:"濱海托薩海岸古城", subtitle:"巴塞隆納往返｜海岸、中世紀城牆與老城", events:[
    { id:"d16-1", time:"07:30", title:"早餐、前往巴塞隆納北站", note:"移動：地鐵／計程車。提前 20–30 分到站", location:"早餐、前往巴塞隆納北站, 巴塞隆納, Spain", kind:"food" },
    { id:"d16-2", time:"08:30–10:00", title:"巴塞隆納 → 濱海托薩", note:"移動：直達巴士約 1.5 小時。單程約 €13–18", kind:"transit" },
    { id:"d16-3", time:"10:00–12:00", title:"大海灘、中世紀城牆、老城", note:"免費", location:"大海灘、中世紀城牆、老城, 巴塞隆納, Spain", kind:"spot" },
    { id:"d16-4", time:"12:00–13:30", title:"海邊午餐", note:"熱門餐廳可訂位", location:"海邊午餐, 巴塞隆納, Spain", kind:"food" },
    { id:"d16-5", time:"13:30–16:00", title:"燈塔、海岸步道、自由活動", note:"穿防滑鞋", kind:"rest" },
    { id:"d16-6", time:"16:30–18:00", title:"返回巴塞隆納", note:"移動：直達巴士。回程先訂位", kind:"transit" },
    { id:"d16-7", time:"19:00", title:"晚餐、休息", note:"翌日購物逛街與伴手禮採買", location:"晚餐、休息, 巴塞隆納, Spain", kind:"food" },
  ]},
  { id:"day-17", date:"2026-10-02", weekday:"五", theme:"購物逛街・伴手禮", subtitle:"巴塞隆納｜悠閒採買、退稅整理與行李打包", events:[
    { id:"d17-shop-1", time:"09:00", title:"早餐、整理購物清單", note:"確認伴手禮、尺寸與退稅需求", location:"早餐, 巴塞隆納, Spain", kind:"food" },
    { id:"d17-shop-2", time:"10:00–12:00", title:"格拉西亞大道購物", note:"百貨、國際品牌與西班牙品牌集中，先購買需要試穿的品項", location:"Passeig de Gràcia, Barcelona, Spain", kind:"spot" },
    { id:"d17-shop-3", time:"12:00–13:00", title:"加泰隆尼亞廣場、英國宮百貨", note:"可集中採買食品、橄欖油、火腿與伴手禮", location:"El Corte Inglés Plaça de Catalunya, Barcelona, Spain", kind:"spot" },
    { id:"d17-shop-4", time:"13:00–14:00", title:"午餐、休息", note:"把已購物品先整理，避免下午提太多行李", location:"加泰隆尼亞廣場, 巴塞隆納, Spain", kind:"food" },
    { id:"d17-shop-5", time:"14:30–16:30", title:"天使門大道與舊城小店", note:"選購在地品牌、皮件、設計雜貨與紀念品", location:"Avinguda del Portal de l'Àngel, Barcelona, Spain", kind:"spot" },
    { id:"d17-shop-6", time:"16:30–18:00", title:"最後採買、整理退稅單", note:"核對護照姓名、收據與退稅文件，商品先不要拆封", kind:"rest" },
    { id:"d17-shop-7", time:"18:30", title:"旅程最後晚餐", note:"選飯店附近餐廳，避免隔天離境前太晚回房", location:"加泰隆尼亞廣場, 巴塞隆納, Spain", kind:"food" },
    { id:"d17-shop-8", time:"20:00", title:"返回飯店、完整打包", note:"分開護照、票券、退稅商品與登機隨身物品", kind:"rest" },
  ]},
  { id:"day-18", date:"2026-10-03", weekday:"六", theme:"巴塞隆納離境", subtitle:"離境日｜住宿基準：擴展區／加泰隆尼亞廣場", events:[
    { id:"d18-1", time:"08:30-09:30", title:"早餐", note:"確認航廈與 機場巴士 路線", location:"早餐, 離境日, Spain", kind:"food" },
    { id:"d18-2", time:"09:30-10:00", title:"退房、寄放行李", note:"移動：飯店。護照與電子票不要放行李箱", kind:"transit" },
    { id:"d18-3", time:"10:00-11:15", title:"飯店附近咖啡／短散步", note:"移動：步行 5-15 分。不安排排隊景點", location:"飯店附近咖啡／短散步, 離境日, Spain", kind:"food" },
    { id:"d18-4", time:"11:15-11:45", title:"回飯店取行李、最後檢查", note:"護照、錢包、手機、充電器", location:"回飯店取行李、最後檢查, 離境日, Spain", kind:"spot" },
    { id:"d18-5", time:"12:00", title:"加泰隆尼亞廣場 出發", note:"移動：T1 搭 機場巴士 A1；T2 搭 A2。車程約 35-45 分｜機場巴士近期約 €8–10／人", kind:"transit" },
    { id:"d18-6", time:"12:45-13:15", title:"抵達 BCN、辦理報到", note:"移動：機場內步行。國際航班預留 3 小時｜機場內無門票", kind:"transit" },
    { id:"d18-7", time:"13:15-15:15", title:"行李托運、安檢、退稅", note:"移動：機場內步行。退稅商品依規定出示", location:"行李托運、安檢、退稅, 離境日, Spain", kind:"spot" },
    { id:"d18-8", time:"15:15", title:"抵達登機門", note:"不要等到最後", kind:"transit" },
    { id:"d18-9", time:"16:15", title:"班機離開巴塞隆納", note:"旅程結束", location:"班機離開巴塞隆納, 離境日, Spain", kind:"spot" },
  ]},
];
